# .github/workflows/ingest.yml

on:
  schedule:
    - cron: '0 3 * * *'  # Daily at 3 AM UTC
  workflow_dispatch:

jobs:
  full-ingest:
    runs-on: ubuntu-latest

    steps:
    - name: 📥 Checkout Repo
      uses: actions/checkout@v3

    - name: 🐍 Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: 📦 Install Dependencies
      run: pip install -r requirements.txt

    - name: 🔐 Setup SSH Private Key
      env:
        TOAST_SFTP_PRIVATE_KEY_B64: ${{ secrets.TOAST_SFTP_PRIVATE_KEY_B64 }}
      run: |
        mkdir -p ~/.ssh
        echo "$TOAST_SFTP_PRIVATE_KEY_B64" | base64 -d > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa

    - name: 📡 Run Toast SFTP Fetch
      env:
        TOAST_SFTP_HOST: ${{ secrets.TOAST_SFTP_HOST }}
        TOAST_SFTP_USERNAME: ${{ secrets.TOAST_SFTP_USERNAME }}
      run: python signalfetch.py

    - name: 📝 Commit New Exported Files
      run: |
        git config --global user.name "github-actions"
        git config --global user.email "github-actions@users.noreply.github.com"
        git add toast_exports/
        git commit -m "⬆️ Daily Toast data sync" || echo "No changes to commit"
        git push

    - name: 🛢️ Ingest to GCP PostgreSQL
      env:
        DATABASE_URL: ${{ secrets.DATABASE_URL }}
      run: python ingest_to_gcp.py
