name: Toast Data Ingestion to Neon

on:
  workflow_dispatch:
  schedule:
    - cron: '0 3 * * *'  # Daily at 3 AM UTC

jobs:
  toast_to_neon:
    runs-on: ubuntu-latest
    env:
      NEON_HOST: ${{ secrets.NEON_HOST }}
      NEON_DB: ${{ secrets.NEON_DB }}
      NEON_USER: ${{ secrets.NEON_USER }}
      NEON_PASSWORD: ${{ secrets.NEON_PASSWORD }}
      TOAST_SFTP_HOST: ${{ secrets.TOAST_SFTP_HOST }}
      TOAST_SFTP_USERNAME: ${{ secrets.TOAST_SFTP_USERNAME }}
      TOAST_SFTP_PRIVATE_KEY_B64: ${{ secrets.TOAST_SFTP_PRIVATE_KEY_B64 }}

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Requirements
        run: pip install -r requirements.txt

      - name: Run Neon Ingest
        run: python neon_ingest.py
