Ingest Toast CSV into Neon

on:
  workflow_dispatch:
  schedule:
    - cron: '0 * * * *'  # hourly

jobs:
  ingest:
    runs-on: ubuntu-latest
    env:
      NEON_HOST: ${{ secrets.NEON_HOST }}
      NEON_DB: ${{ secrets.NEON_DB }}
      NEON_USER: ${{ secrets.NEON_USER }}
      NEON_PASSWORD: ${{ secrets.NEON_PASSWORD }}
      TOAST_SFTP_HOST: ${{ secrets.TOAST_SFTP_HOST }}
      TOAST_SFTP_USERNAME: ${{ secrets.TOAST_SFTP_USERNAME }}
      TOAST_SFTP_PRIVATE_KEY_B64: ${{ secrets.TOAST_SFTP_PRIVATE_KEY_B64 }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install paramiko psycopg2-binary

      - name: Run Neon ingestion
        run: python neon_ingest.py
